# Generated by Django 3.2.5 on 2022-08-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='TipoCuenta',
        ),
    ]
